on: [ push ]
name: Lint Python and Format
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install . mypy
      - name: run mypy
        run: python -m mypy --strict 
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install . flake8
      - name: run flake8
        run: python -m flake8
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install black
      - name: Check formating with black
        run: python -m black --check .
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install . pytest
      - name: Run tests
        run: python -m pytest test

