on: [ push ]
name: Lint Python and Format
jobs:
  mypy:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install . mypy
      - name: run mypy
        run: python3 -m mypy --strict 
  flake8:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install . flake8
      - name: run flake8
        run: python3 -m flake8
  black:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install black
      - name: Check formating with black
        run: python3 -m black --check .
  pytest:
      runs-on: ubuntu-latest
      container:
        image: python:3.10
      steps:
        - uses: actions/checkout@v2
        - run: |
            apt-get update 
            apt install -y clang-14
        - run: pip3 install . pytest
        - name: Run tests
          run: python3 -m pytest test

